stages:
  - test
  - scrape
  - deploy

test:
  stage: test
  image: python:3.8-alpine
  timeout: "2 minutes"
  before_script:
    - ./scripts/install
  script:
    - ./scripts/test

scrape:
  stage: scrape
  image: python:3.8-alpine
  timeout: "5 minutes"
  tags:
    - ovh
  before_script:
    - apk add --update make
    - ./scripts/install
  script:
    - ./scripts/scrape
    - make stats
  artifacts:
    name: "rdv"
    paths:
      - data/output
  only:
    - master
    - gitlab-publish
    - schedules

pages:
  stage: deploy
  image: python:3.8-alpine
  tags:
    - ovh
  script:
    - mkdir -p public
    - cp data/output/* public/
    - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
