
---
name: Cron Ordoclic

on:
  workflow_run:
    workflows: ["Scrap Ordoclic"]
    types:
      - completed

jobs:
  sleep:
    name: "Sleep"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Sleep 120s"
        run: sleep 120