---
name: Doctolib center scrap

on:
  push:
    branches: ["ft/doctoscrap"]
  workflow_dispatch:

jobs:

  scrape:
    name: "Doctolib center scrap"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
            token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: make install
      - name: "Doctolib scrap..."
        run: make doctoscrap
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Update
          push_options: '--force HEAD:data-auto'
