---
name: Doctolib center scrap

on:
  schedule:
    - cron: "0 * * * *"
  # Allow running manually
  workflow_dispatch:

jobs:

  scrape:
    name: "Doctolib center scrap"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
            token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: make install
      - name: "Doctolib scrap..."
        run: make doctoscrap
      - name: "Pull from data-auto"
        run: git pull origin data-auto
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: data/output/doctolib-centers.json
          commit_message: Updated Doctolib centers
