---
name: Linter

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    name: Linter
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.4.0
