
---
name: Scrap Doctolib

on:
## Disabled. Enable if emergency
 #  push:
 #    branches:
 #      - data-auto
 #  schedule:
 #    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  scrape_doctolib:

    name: "Scrape Doctolib"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: "actions/checkout@v2"
        with:
            token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: scripts/install
      - name: "Scraping Doctolib..."
        run: |
          scripts/scrape -p doctolib
          cp data/output/pool/doctolib.json /tmp/doctolib.json
      - name: Switch to data-auto
        run: |
          git switch origin data-auto
          cp /tmp/doctolib.json data/output/pool/doctolib.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Automatic Update
            file_pattern: data/output/pool/doctolib.json