---
name: Scrap Mapharma

on:
## Disabled. Enable if emergency
 #  push:
 #    branches:
 #      - data-auto
 #  schedule:
 #    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  scrape_mapharma:

    name: "Scrape Mapharma"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: "actions/checkout@v2"
        with:
            token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: scripts/install
      - name: "Scraping Mapharma..."
        run: |
          scripts/scrape -p mapharma
          cp data/output/pool/mapharma.json /tmp/mapharma.json
      - name: "Switch to data-auto"
        run: |
          git fetch --all --prune --force
          git reset --hard origin/data-auto
          git switch data-auto
          cp /tmp/mapharma.json data/output/pool/mapharma.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Automatic Update
            file_pattern: data/output/pool/mapharma.json
