---
name: Scrap Doctolib

on:
## Disabled. Enable if emergency
 #  push:
 #    branches:
 #      - data-auto
 #  schedule:
 #    - cron: "*/5 * * * *"
  push:
    branches:
      - ft/scraperpool # while working on this
  workflow_dispatch:

jobs:

  scrape_doctolib:

    name: "Scrape Doctolib"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: "actions/checkout@v2"
        with:
            token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: scripts/install
      - name: "Scraping Doctolib..."
        run: scripts/scrape -p doctolib
      - name: Run git status (debug)
        run: git status