name: Test

on:
  push:
    branches: ["main", "ft/readme"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install dependencies"
        run: scripts/install
      - name: "Run tests"
        run: scripts/test
      - name: "Generate coverage badge"
        run: coverage-badge